name: Release
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm i
      - name: Run Tests
        run: |
          npm run test
      - name: Build
        run: npm run build
      - run: 'sed -i "s/\(.name.:.*,\)/\1\n  \"version\": \""${{ github.event.release.tag_name }}"\", /" package.json'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}